FROM tensorflow/tensorflow:1.15.0-gpu

RUN pip install tf-slim
RUN pip install scipy
RUN pip install imageio==2.6.1
RUN pip install numpy
RUN pip install scikit-image
RUN pip install pathlib

WORKDIR /opt/project/Code/